# Generated by Django 4.2 on 2023-05-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_alter_usuario_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
