# Generated by Django 4.1.2 on 2022-12-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_usuario_delete_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
