# Generated by Django 4.1.2 on 2023-01-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('ip', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=15)),
            ],
        ),
    ]
