# Generated by Django 4.2.1 on 2023-05-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0004_estados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intentos',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('intentos', models.PositiveIntegerField()),
                ('fecha_ultimo_intento', models.DateTimeField()),
            ],
        ),
    ]
